language: java
os:
- linux
dist: focal
jdk:
- openjdk11
cache:
  directories:
  - $HOME/.m2/repository/_inofficial/com/github/vatsimnetwork/vatspy-data-project/
install: ./install-unpublished-dependencies.sh && mvn clean install
script: /bin/true
deploy:
  provider: releases
  edge: true
  token: $GH_DEPLOY_API_KEY
  file: target/legacy-status-proxy-vatsim.jar
  cleanup: false
  name: Draft $TRAVIS_TAG / Travis Build $TRAVIS_BUILD_NUMBER
  draft: true
  on:
    tags: true
